version: "2"
services:
  web:
    image: node:8.9.4
    privileged: true
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    volumes: 
    - ./:/usr/src/app
  mongo:
    image: mongo:3.6.23
    privileged: true
    ports:
    - "27017:27017"
    volumes:
    - ./mongo:/data/db