version: "3.8"
services:
  nodejs:
    image: my_nodejs
    container_name: lab_js
    build:
      context: .
      dockerfile: ./Dockerfile
    privileged: true
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    volumes: 
    - ./:/usr/src/app
    networks:
      - node-mongo
  mongo:
    image: mongo:4.2
    hostname: mongo123
    container_name: lab_mongo
    privileged: true
    ports:
    - "27017:27017"
    volumes:
      - type: volume
        source: mongoDB
        target: /data/db
    networks:
      - node-mongo
networks:
  node-mongo:
volumes:
  mongoDB:
